### ISSUE TITLE
Teensy 3.6 pin 17 not working

### ISSUE THREAD

**Issue by MangaValk** [PaulStoffregen/PWMServo#2]
### Description

Describe your problem.
On the teensy 3.6 pin 16 and 17 will not attach, digitalPinHasPWM returns false.
According to the manual pin 16 and 17 should work.

### Steps To Reproduce Problem

Please give detailed instructions needed for anyone to attempt to reproduce the problem.
Attach a servo to pin 16 or 17 and print the result of attach.

### Hardware & Software

Board Teensy 3.6
Shields / modules used none
Arduino IDE version 1.8.9
Teensyduino version (if using Teensy) 
Version info & package name (from Tools > Boards > Board Manager)
Operating system & version
Any other software or hardware?

### Arduino Sketch

```cpp
// Change the code below by your sketch (please try to give the smallest code which demonstrates the problem)
#include "PWMServo.h"

PWMServo servostest;

void setup() {
Serial.begin(115200);
Serial.println(servostest.attach(17));
}

void loop() {
servostest.write(90);
}
```

### Errors or Incorrect Output

If you see any errors or incorrect output, please show it here.  Please use copy & paste to give an exact copy of the message.  Details matter, so please show (not merely describe) the actual message or error exactly as it appears.

**Comment by MangaValk** [comment]
I was searching through the Teensy source code myself to possibly write a fix for everyone.
I found out that the digitalPinHasPWM for the teensy 3.6 board isn't correct compared to the documentation. https://github.com/PaulStoffregen/cores/blob/fc79132670ac83ce7cae8e2bac64be109fbfe35e/teensy3/pins_arduino.h#L179

**Comment by PaulStoffregen** [comment]
Fixed
https://github.com/PaulStoffregen/cores/commit/63aba265dbd7df55d366da4ed6af2c0a62df3f32

**Comment by MangaValk** [comment]
Many thanks! 
Can't try it now since I'm away from home.
Love your teensy 3.6 board!

**Comment by Akhaides** [comment]
#corelib 1  @buildprop "lesson 16"

**Comment by PaulStoffregen** [comment]
Verified this is working.  Closing this old issue.

![file](https://user-images.githubusercontent.com/965463/81059992-72bd6c80-8e86-11ea-9133-fb7c7f23dac5.png)
